---
- yum: 
   name: httpd
   state: present
- copy:
    src: index.html
    dest: /var/www/html/
  notify:
    - restart httpd
- name: restart httpd
  service:
     name: httpd
     state: started



